server {
    listen 80;
    server_name vladiksfriendsprofilebot.webtm.ru;
    return 301 https://$host$request_uri;
}

server {
    server_name vladiksfriendsprofilebot.webtm.ru;
    listen 443 ssl;
    http2 on;
    ssl_certificate /etc/letsencrypt/live/vladiksfriendsprofilebot.webtm.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vladiksfriendsprofilebot.webtm.ru/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

