version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"  # Для API
    restart: unless-stopped

  tma:
    container_name: tma-app
    build: ./tma
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      NODE_ENV: production
    restart: unless-stopped