services:
  bot:
    build: ./bot
    container_name: bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  api:
    build: ./api
    container_name: api
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  tma:
    build: ./tma
    image: nginx:alpine
    container_name: tma
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    restart: unless-stopped